# Generated by Django 4.1.4 on 2022-12-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0002_alter_gif_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gif',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
